name: Release

on:
  push:
    tags:
      - "v*"
env:
  proj-name: hsco

jobs:
  build_release:
    name: ${{ matrix.os }}/${{ github.ref }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set tag name
        uses: olegtarasov/get-tag@v2.1.4
        id: tag
        with:
          tagRegex: "v(.*)"
          tagRegexGroup: 1

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        id: setup-haskell-stack
        with:
          enable-stack: true
          stack-no-global: true

      - name: Cache ./.stack-work
        uses: actions/cache@v4
        with:
          path: |
            ./.stack-work
            ${{ setup-haskell-stack.outputs.stack-root }}
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}

      - name: Build binary
        run: |
          mkdir dist
          stack --local-bin-path dist install

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ env.proj-name }}.exe
